SELECT A.ID
FROM (
    SELECT ID, PARENT_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IN (SELECT ID FROM ECOLI_DATA WHERE PARENT_ID IN (
                        SELECT ID FROM ECOLI_DATA WHERE PARENT_ID IS NULL))
) AS A
ORDER BY 1;


# SELECT F.ID, F.PARENT_ID, S.ID, S.PARENT_ID, T.ID, T.PARENT_ID
# FROM ECOLI_DATA AS F, ECOLI_DATA AS S, ECOLI_DATA AS T
# WHERE F.PARENT_ID = S.ID and S.PARENT_ID = T.ID and T.PARENT_ID IS NULL
# ORDER BY 1;