SELECT
    e.ID,
    CASE 
        WHEN (e2.NUM / (SELECT COUNT(*) FROM ECOLI_DATA)) * 100 BETWEEN 0 AND 25 THEN 'CRITICAL'
        WHEN (e2.NUM / (SELECT COUNT(*) FROM ECOLI_DATA)) * 100 <= 50 THEN 'HIGH'
        WHEN (e2.NUM / (SELECT COUNT(*) FROM ECOLI_DATA)) * 100 <= 75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS 'COLONY_NAME'
FROM ECOLI_DATA e
JOIN (
      SELECT ROW_NUMBER() OVER (ORDER BY SIZE_OF_COLONY DESC) AS NUM, ID, SIZE_OF_COLONY
      FROM ECOLI_DATA) e2
ON e.ID = e2.ID
ORDER BY e.ID;
