/*
SKILLCODES(프로그래밍 언어 정보) : *NAME*, CATEGORY, *CODE*
DEVELOPERS(개발자 기술 스택) : *ID*, FIRST_NAME, LAST_NAME, *EMAIL*, SKILL_CODE
ㄴ POINT : SKILLCODES.CODE 는 2의 제곱수로 구성됨.
ㄴ POINT : DEVELOPERS.SKILL_CODE 는 2진수로 표현할 때 각 bit는 기술스택을 의미함.
*/

SELECT ID,	EMAIL,	FIRST_NAME,	LAST_NAME
FROM DEVELOPERS
WHERE SKILL_CODE & (
    SELECT SUM(CODE)
    FROM SKILLCODES
    WHERE NAME IN ('Python', 'C#')
)
ORDER BY ID;
